title: <p align="center"> Mohinesh Tayade </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mohinesh-tayade/">LinkedIn</a> |
  <a href="https://github.com/mohinesh27">GitHub</a>
  
  <br>   
  I'm working as fullstack developer on technologies like .net, nodejs, python, Angular, MS SQL, MongoDB with cloud platforms like AWS, Azure, GCP also Data Science and AI ML enthusiast.
  Working in The Toro Company from last 4 years.
  <br>
  </p>



theme: jekyll-theme-minimal
